FROM index.docker.io/library/caddy:builder AS builder

RUN xcaddy build --with github.com/caddy-dns/gandi

FROM index.docker.io/library/caddy:2

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

COPY Caddyfile.homelab /etc/caddy/Caddyfile
